Require recent bytestring with ghc-8.0 or later
This is somewhat band-aid solution for:

Data/Aeson/Encoding/Builder.hs:87:21: error:
    • No instance for (Semigroup Builder) arising from a use of ‘<>’

But there aren't better solution: we don't include anything
from semigroups on ghc >= 8.0; so semigroups couldn't even
in theory provide that instance.

Also a lot of older aeson releases are "broken" because of this,
if one downgrades bytestring. Usually no-one does that, except weird
automatic QA tools.